version: '3'

services:
    redis:
        image: redis
        ports:
            - 6379
    front:
        image: frontend:latest
        ports:
            - 5000:5000
    back:
        image: backend:latest
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379