version: '3'

services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=passu
            - POSTGRES_USER=user
            - DB_NAME=postgres
    redis:
        image: redis
        ports:
            - 6379
    front:
        image: frontend:latest
        ports:
            - 5000:5000
    back:
        image: backend:latest
        ports:
            - 8000:8000
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=user
            - DB_PASSWORD=passu
            - DB_NAME=postgres
            - DB_HOST=database